### PR TITLE
More Platforms

### PR DESCRIPTION
**Pull request by Zunnurayni**

### CODE REVIEW

**Comment by melroy89** [comment]
Why so much new lines at the end?? Please keep only 1 new line at the end of the file.

**Comment by melroy89** [comment]
Maybe also update all reference of "Bitcoincash" to "Bitcoin Cash" (so with a space and capital letter B and capital letter C)

**Comment by Zunnurayni** [comment]
Okay will take note of that .

**Comment by melroy89** [comment]
It's not solved yet. I can't merge this.

**Comment by Zunnurayni** [comment]
whats still wrong with it , i fixed the typos

**Comment by Zunnurayni** [comment]
whats still wrong with it , i fixed the typos

**Comment by melroy89** [comment]
Change all "BitcoinCash" instances to "Bitcoin Cash". And remove all the enters at the end of the file only leave 1 new line, not 10 new lines.

**Comment by melroy89** [comment]
Never mind... I will fix it.. You are taking too long. Next time create a better PR please.

**Pull request merged**
